const COMMAND_GATEWAY_LOW_RISK_COMMANDS = new Set([
  "requestHistoryDictionaryTerm",
  "saveStudentHistoryDictionaryWord",
  "saveStudentHistoryDictionaryEntry",
  "deleteStudentHistoryDictionaryWord",
  "saveHistoryDictionaryTermsBulk",
  "createTeacherPatchNote",
  "updateTeacherPatchNote",
  "updateTeacherPatchNoteStatus",
  "deleteTeacherPatchNote",
  "saveLessonAnswers",
  "startAssessmentAttempt",
  "submitAssessmentAttempt",
  "requestGradeReview",
  "acknowledgeGradeEvidence",
  "placeWisOrder",
  "recordLearningProgress",
  "requestLearningExemption",
  "acknowledgeNotice",
  "acknowledgeAllNotices",
  "saveTeacherDraft",
  "discardTeacherDraft",
  "resolveTeacherDraft",
]);

const COMMAND_GATEWAY_HIGH_RISK_COMMANDS = [
  "approveStudentRegistration",
  "updateStudentEnrollmentProfile",
  "migrateLegacyWisAccount",
  "saveHistoryDictionaryTerm",
  "approveHistoryDictionaryTermForRequests",
  "updateStudentHistoryDictionaryWordByTeacher",
  "deleteStudentHistoryDictionaryWordByTeacher",
  "saveMapResources",
  "deleteMapResource",
  "prepareMapAssetUpload",
  "prepareSourceArchiveUpload",
  "saveSourceArchiveMetadata",
  "deleteSourceArchiveAsset",
  "saveLessonDocument",
  "saveLessonTree",
  "prepareLessonAssetUpload",
  "updateTermsSettings",
  "addConsentItem",
  "updateConsentItem",
  "deleteConsentItem",
  "syncKoreanPublicHolidays",
  "adjustTeacherPoints",
  "createSemesterManifest",
  "updateSemesterManifest",
  "updateOperationalSettings",
  "validateSemesterReadiness",
  "transitionSemesterStatus",
  "activateSemester",
  "createSemesterClass",
  "updateSemesterClass",
  "importEnrollmentRoster",
  "upsertEnrollment",
  "moveEnrollment",
  "closeEnrollment",
  "prepareSemesterArchive",
  "freezeSemesterArchive",
  "createAssessmentDefinition",
  "updateAssessmentDefinition",
  "transitionAssessmentDefinition",
  "resetAssessmentAttemptsByClassV2",
  "resetAssessmentAttempt",
  "upsertQuizQuestion",
  "deleteQuizQuestion",
  "upsertHistoryClassroomSource",
  "deleteHistoryClassroomSource",
  "updateMapResourceBlanks",
  "createGradeDraft",
  "reviewGradeDraft",
  "finalizeGradeEvidence",
  "publishOfficialGrade",
  "correctOfficialGrade",
  "signOfficialGrade",
  "createSemesterEconomy",
  "createWisAccounts",
  "grantInitialWis",
  "grantWis",
  "deductWis",
  "adjustWis",
  "reverseWisEntry",
  "rebuildWisProjection",
  "transitionWisEconomy",
  "upsertWisProduct",
  "upsertWisInventory",
  "reviewWisOrder",
  "createLearningContent",
  "updateLearningContent",
  "transitionLearningContent",
  "resetLearningProgress",
  "grantLearningExemptions",
  "revokeLearningExemptions",
  "reviewLearningExemptionRequest",
  "createScheduleEvent",
  "updateScheduleEvent",
  "deleteScheduleEvent",
  "createAttendanceSession",
  "recordAttendance",
  "recordAttendanceBulk",
  "correctAttendanceRecord",
  "closeAttendanceSession",
  "createNotice",
  "updateNotice",
  "transitionNotice",
  "updateNotificationSettings",
  "cleanupExpiredTeacherDrafts",
  "createTeacherBulkJob",
  "reconcileTeacherBulkJob",
  "retryTeacherBulkJob",
  "createSemesterCutoverPlan",
  "dryRunSemesterCutover",
  "applySemesterCutoverBatch",
  "verifySemesterCutover",
  "resumeSemesterCutover",
  "createSemesterRollbackPlan",
] as const;

export const HIGH_RISK_COMMANDS = new Set<string>([
  "uploadMapAssetContent",
  "uploadSourceArchiveAsset",
  "cleanupSourceArchiveAsset",
  "uploadLessonAssetContent",
  ...COMMAND_GATEWAY_HIGH_RISK_COMMANDS,
  // Retained direct-callable names that have not yet moved to the gateway.
  "deleteStudentData",
  "updateStudentData",
  "resetAssessmentAttemptsByClass",
  "resetQuizAttemptsForClass",
  "recalculateQuizResultsAfterQuestionCorrection",
  "grantHistoryClassroomExemptions",
  "revokeHistoryClassroomExemptions",
  "reviewHistoryClassroomExemptionRequest",
  "reviewPerformanceScoreObjection",
  "saveWisHallOfFameConfig",
  "rebuildPointWalletRankTotals",
  "updateTeacherPointAdjustment",
  "reviewTeacherPointOrder",
  "deleteSourceArchiveAsset",
  "previewEnrollmentRoster",
]);

export const isHighRiskCommand = (commandName: string) =>
  HIGH_RISK_COMMANDS.has(String(commandName || "").trim());

/**
 * The command gateway fails closed for unknown command names. Only commands
 * whose server adapters explicitly use a general application session may skip
 * step-up reauthentication.
 */
export const requiresCommandGatewayStepUpReauthentication = (
  commandName: string,
) => !COMMAND_GATEWAY_LOW_RISK_COMMANDS.has(String(commandName || "").trim());
